valor = int(input('Dígite qual tabuada deseja: '))
print('Tabuada do', valor)
print(valor,'. 1 =',valor*1)
print(valor,'. 2 =',valor*2)
print(valor,'. 3 =',valor*3)
print(valor,'. 4 =',valor*4)
print(valor,'. 5 =',valor*5)
print(valor,'. 6 =',valor*6)
print(valor,'. 7 =',valor*7)
print(valor,'. 8 =',valor*8)
print(valor,'. 9 =',valor*9)
print(valor,'. 10 =',valor*10)